# Re-export from core constants for convenience
from app.core.constants import (
    ROLE_ADMIN,
    ROLE_USER,
    USER_ROLES,
    ACCESS_TOKEN,
    REFRESH_TOKEN,
)

# Auth-specific error codes
AUTH_ERROR_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
AUTH_ERROR_USER_EXISTS = "USER_ALREADY_EXISTS"
AUTH_ERROR_USER_NOT_FOUND = "USER_NOT_FOUND"
AUTH_ERROR_INVALID_TOKEN = "INVALID_TOKEN"
AUTH_ERROR_TOKEN_EXPIRED = "TOKEN_EXPIRED"
AUTH_ERROR_TOKEN_REVOKED = "TOKEN_REVOKED"
AUTH_ERROR_WEAK_PASSWORD = "WEAK_PASSWORD"
AUTH_ERROR_INACTIVE_USER = "INACTIVE_USER"
AUTH_ERROR_FORBIDDEN = "FORBIDDEN"
