import React, { useCallback, useEffect, useState } from 'react';

const API = 'http://localhost:8000/api/v1/career-coach';
const token = () => localStorage.getItem('ai_career_access_token') || localStorage.getItem('token');
async function api(path, options = {}) {
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token() ? { Authorization: `Bearer ${token()}` } : {}), ...(options.headers || {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.detail || 'The coach could not complete that action.');
  return data;
}
const TABS = [['overview', 'Overview'], ['chat', 'AI chat'], ['gaps', 'Gap analysis'], ['roadmap', 'Roadmap'], ['jobs', 'Job strategy'], ['resume', 'Resume coach'], ['interview', 'Interview coach'], ['decisions', 'Decisions']];
const PROMPTS = ['Analyze my career', 'What should I do today?', 'Why am I not getting interviews?', 'Create my 90-day roadmap', 'Am I ready for my target role?'];
function ScoreBar({ label, value }) { return <div className="coach-score-row"><div><span>{label}</span><strong>{value ?? 0}</strong></div><div className="coach-progress"><i style={{ width: `${Math.max(0, Math.min(100, value || 0))}%` }} /></div></div>; }
function Button({ children, className = '', ...props }) { return <button className={`coach-button ${className}`} {...props}>{children}</button>; }

export default function AICoach() {
  const [tab, setTab] = useState('overview'), [data, setData] = useState({}), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [chatText, setChatText] = useState(''), [messages, setMessages] = useState([]), [roadmapDays, setRoadmapDays] = useState(90), [roadmap, setRoadmap] = useState(null);
  const [resumeJobId, setResumeJobId] = useState(''), [resume, setResume] = useState(null), [jobId, setJobId] = useState(''), [job, setJob] = useState(null);
  const [interview, setInterview] = useState(null), [answer, setAnswer] = useState(''), [evaluation, setEvaluation] = useState(null), [decisionText, setDecisionText] = useState('Should I change jobs?'), [decision, setDecision] = useState(null);
  const load = useCallback(async () => { if (!token()) return; setError(''); try { const [profile, health, brief, insights, gaps] = await Promise.all([api('/profile'), api('/health'), api('/brief'), api('/insights'), api('/gap-analysis')]); setData({ profile, health, brief, insights, gaps }); } catch (e) { setError(e.message); } }, []);
  useEffect(() => { load(); }, [load]);
  const run = async action => { setBusy(true); setError(''); try { await action(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const startAction = () => run(async () => { const action = data.brief?.next_action; if (!action) return; await api('/next-action/start', { method: 'POST', body: JSON.stringify(action) }); await load(); });
  const updateTask = (id, status) => run(async () => { await api(`/tasks/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); });
  const sendChat = (message = chatText) => run(async () => { if (!message.trim()) return; setMessages(prev => [...prev, { role: 'user', text: message }]); setChatText(''); const response = await api('/chat', { method: 'POST', body: JSON.stringify({ message }) }); setMessages(prev => [...prev, { role: 'coach', text: response.answer, confidence: response.confidence }]); });
  const generateRoadmap = () => run(async () => { setRoadmap(await api('/roadmap', { method: 'POST', body: JSON.stringify({ days: Number(roadmapDays) }) })); await load(); });
  const analyzeResume = () => run(async () => setResume(await api(`/resume-analysis${resumeJobId ? `?job_id=${resumeJobId}` : ''}`, { method: 'POST' })));
  const analyzeJob = () => run(async () => { if (!jobId) throw new Error('Enter a job ID from your saved Jobs module.'); setJob(await api(`/job-analysis/${jobId}`, { method: 'POST' })); });
  const startInterview = mode => run(async () => { setInterview(await api('/interview', { method: 'POST', body: JSON.stringify({ mode }) })); setEvaluation(null); setAnswer(''); });
  const submitAnswer = () => run(async () => { if (!interview || !answer.trim()) throw new Error('Write an answer before asking for feedback.'); setEvaluation(await api(`/interview/${interview.interview_id}/answer`, { method: 'POST', body: JSON.stringify({ question_id: interview.question_id, answer }) })); });
  const makeDecision = () => run(async () => setDecision(await api('/decision', { method: 'POST', body: JSON.stringify({ question: decisionText }) })));
  const profile = data.profile || {}, health = data.health || { metrics: {} }, next = data.brief?.next_action, tasks = data.brief?.tasks || [];
  return <section id="viewAiCoach" className="app-view coach-view" style={{ display: 'none' }}><div className="coach-shell">
    <aside className="coach-nav"><div className="coach-nav-title"><span>✦</span><div><strong>AI Career Coach</strong><small>Execution intelligence</small></div></div>{TABS.map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</aside>
    <div className="coach-main"><header className="coach-header"><div><p className="coach-eyebrow">PERSONAL CAREER STRATEGY</p><h1>AI Career Coach</h1><p>Your personal AI strategist for building, navigating, and accelerating your career.</p></div><Button onClick={() => run(load)} disabled={busy}>Refresh analysis</Button></header>{error && <div className="coach-error">{error}</div>}
    {tab === 'overview' && <><div className="coach-context-grid"><div><span>Career stage</span><strong>{profile.career_stage || 'Set up your profile'}</strong></div><div><span>Target role</span><strong>{profile.target_role || 'Not defined'}</strong></div><div><span>Career health</span><strong>{health.total_score ?? '—'}<small>/100</small></strong></div><div><span>Last analysis</span><strong>{health.calculated_at ? new Date(health.calculated_at).toLocaleDateString() : 'Not analyzed'}</strong></div></div><div className="coach-grid coach-overview-grid"><article className="coach-card coach-health"><div className="coach-card-title"><div><p>CAREER HEALTH</p><h2>{health.total_score ?? 0}<small>/100</small></h2></div><span className="coach-coverage">{health.data_coverage || 0}/10 signals</span></div><div className="coach-score-list">{Object.entries(health.metrics || {}).map(([name, value]) => <ScoreBar key={name} label={name} value={value} />)}</div></article><article className="coach-card coach-next"><p className="coach-eyebrow">YOUR NEXT BEST CAREER ACTION</p><h2>{next?.title || 'Loading your highest-value action…'}</h2><p>{next?.rationale}</p><div className="coach-tags"><span>{next?.impact || '—'} impact</span><span>{next?.estimated_minutes || '—'} min</span><span>{next?.confidence || '—'}% confidence</span></div><Button onClick={startAction} disabled={busy || !next}>Start now</Button></article></div><div className="coach-grid coach-two-col"><article className="coach-card"><p className="coach-eyebrow">TODAY'S CAREER PLAN</p><h2>Focused execution</h2>{tasks.length ? <div className="coach-task-list">{tasks.map(task => <div key={task.id} className="coach-task"><div><span className={`coach-priority ${task.priority.toLowerCase()}`}>{task.priority}</span><strong>{task.title}</strong><p>{task.description || 'No further detail yet.'}</p><small>{task.estimated_minutes} minutes · {task.status.replace('_', ' ')}</small></div><div className="coach-task-actions">{task.status !== 'IN_PROGRESS' && <Button onClick={() => updateTask(task.id, 'IN_PROGRESS')} disabled={busy}>Start</Button>}<Button className="secondary" onClick={() => updateTask(task.id, 'COMPLETED')} disabled={busy}>Complete</Button></div></div>)}</div> : <div className="coach-empty"><strong>Nothing scheduled yet.</strong><p>Start the recommended action to create an accountable task.</p><Button onClick={startAction} disabled={busy || !next}>Create today’s plan</Button></div>}</article><article className="coach-card"><p className="coach-eyebrow">WEEKLY CAREER STRATEGY</p><h2>{data.insights?.weekly_strategy?.recommended_focus || 'Preparing your strategy'}</h2><dl className="coach-insights"><div><dt>Biggest opportunity</dt><dd>{data.insights?.weekly_strategy?.biggest_opportunity}</dd></div><div><dt>Biggest risk</dt><dd>{data.insights?.weekly_strategy?.biggest_risk}</dd></div><div><dt>Application signal</dt><dd>{data.insights?.application_strategy?.diagnosis}</dd></div></dl></article></div></>}
    {tab === 'chat' && <article className="coach-card coach-chat"><div><p className="coach-eyebrow">CONTEXT-AWARE STRATEGIST</p><h2>Ask the coach</h2><p>Responses use your Career OS profile, jobs, tasks, learning, interview, resume, and portfolio evidence.</p></div><div className="coach-suggestions">{PROMPTS.map(prompt => <button key={prompt} onClick={() => sendChat(prompt)} disabled={busy}>{prompt}</button>)}</div><div className="coach-messages">{messages.length ? messages.map((message, index) => <div key={index} className={`coach-message ${message.role}`}><small>{message.role === 'coach' ? `AI COACH · ${message.confidence || '—'}% confidence` : 'YOU'}</small><p>{message.text}</p></div>) : <div className="coach-empty"><strong>Start with a strategic question.</strong><p>The coach will say when your data is insufficient instead of inventing an answer.</p></div>}</div><form onSubmit={e => { e.preventDefault(); sendChat(); }} className="coach-composer"><input value={chatText} onChange={e => setChatText(e.target.value)} placeholder="What should I focus on today?" disabled={busy}/><Button disabled={busy || !chatText.trim()}>Ask coach</Button></form></article>}
    {tab === 'gaps' && <article className="coach-card"><p className="coach-eyebrow">WHERE AM I FALLING BEHIND?</p><h2>{data.gaps?.target_role || 'Set a target role to compare your evidence'}</h2><p className="coach-muted">Source: {data.gaps?.source}</p>{data.gaps?.gaps?.length ? <div className="coach-gap-list">{data.gaps.gaps.map(gap => <div key={gap.skill} className="coach-gap"><div><div className="coach-gap-name"><strong>{gap.skill}</strong><span className={`coach-priority ${gap.priority.toLowerCase()}`}>{gap.priority}</span></div><div className="coach-progress"><i style={{ width: `${gap.current_score}%` }}/></div><small>{gap.current_score}% evidence · {gap.estimated_time}</small></div><p><strong>Why it matters:</strong> {gap.why}<br/><strong>Close it:</strong> {gap.how_to_close}</p></div>)}</div> : <div className="coach-empty"><strong>No role-specific gaps yet.</strong><p>{data.gaps?.missing_data?.[0]}</p></div>}</article>}
    {tab === 'roadmap' && <article className="coach-card"><p className="coach-eyebrow">CAREER ROADMAP GENERATOR</p><h2>Turn your target into scheduled execution</h2><div className="coach-controls"><select value={roadmapDays} onChange={e => setRoadmapDays(e.target.value)}><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option><option value="180">6 months</option><option value="365">1 year</option></select><Button onClick={generateRoadmap} disabled={busy}>Generate roadmap</Button></div>{roadmap && <div className="coach-roadmap"><h3>{roadmap.objective}</h3>{roadmap.phases.map((phase, index) => <div className="coach-phase" key={phase.name}><span>{index + 1}</span><div><strong>{phase.name}</strong><p>{phase.description}</p><small>Focus: {phase.focus}</small></div></div>)}</div>}</article>}
    {tab === 'jobs' && <article className="coach-card"><p className="coach-eyebrow">JOB SEARCH STRATEGY</p><h2>Application performance</h2><div className="coach-funnel"><div><strong>{data.insights?.application_strategy?.applications || 0}</strong><span>Applications</span></div><div><strong>{data.insights?.application_strategy?.interviews || 0}</strong><span>Interviews</span></div><div><strong>{data.insights?.application_strategy?.offers || 0}</strong><span>Offers</span></div><div><strong>{data.insights?.application_strategy?.interview_rate ?? '—'}{data.insights?.application_strategy?.interview_rate !== null && '%'}</strong><span>Interview rate</span></div></div><p>{data.insights?.application_strategy?.diagnosis}</p><div className="coach-controls"><input type="number" value={jobId} onChange={e => setJobId(e.target.value)} placeholder="Saved job ID"/><Button onClick={analyzeJob} disabled={busy}>Analyze job match</Button></div>{job && <div className="coach-result"><h3>{job.job_title} · {job.match_score}% match</h3><p>{job.recommendation}</p><div className="coach-tags"><span>Matched: {job.matched.join(', ') || 'No keywords identified'}</span><span>Missing: {job.missing.join(', ') || 'No critical gaps identified'}</span></div></div>}</article>}
    {tab === 'resume' && <article className="coach-card"><p className="coach-eyebrow">RESUME COACH</p><h2>Analyze your resume against your target</h2><div className="coach-controls"><input type="number" value={resumeJobId} onChange={e => setResumeJobId(e.target.value)} placeholder="Optional saved job ID"/><Button onClick={analyzeResume} disabled={busy}>Analyze resume</Button></div>{resume && (resume.available ? <div className="coach-result"><h3>{resume.match_score}% keyword alignment</h3><p><strong>Missing keywords:</strong> {resume.missing_keywords.join(', ') || 'No missing target keywords identified.'}</p><p><strong>Weak bullets:</strong></p>{resume.weak_bullets.length ? <ul>{resume.weak_bullets.map((b, i) => <li key={i}>{b}</li>)}</ul> : <p>There are no bullets to assess or your bullets already contain measurable evidence.</p>}<p className="coach-muted">Apply changes remains intentionally manual: the coach suggests content but does not alter your resume without review.</p></div> : <div className="coach-empty"><strong>{resume.message}</strong></div>)}</article>}
    {tab === 'interview' && <article className="coach-card"><p className="coach-eyebrow">AI INTERVIEW COACH</p><h2>Practice, get scored, improve</h2><div className="coach-suggestions">{['Technical', 'Behavioral', 'System Design', 'Coding', 'HR', 'Case Study'].map(mode => <button key={mode} onClick={() => startInterview(mode.replace(' ', '_'))} disabled={busy}>{mode}</button>)}</div>{interview && <div className="coach-interview"><span className="coach-priority high">{interview.mode.replace('_', ' ')}</span><h3>{interview.question}</h3><textarea value={answer} onChange={e => setAnswer(e.target.value)} placeholder="Write or paste your answer. The coach will evaluate structure, relevance, technical depth, and communication." rows="7"/><Button onClick={submitAnswer} disabled={busy || !answer.trim()}>Evaluate my answer</Button>{evaluation && <div className="coach-result"><h3>{evaluation.overall_score}/100 interview score</h3><div className="coach-score-list">{Object.entries(evaluation.scores).map(([label, value]) => <ScoreBar key={label} label={label} value={value}/>)}</div><p><strong>Improve:</strong> {evaluation.weaknesses.join(' ') || evaluation.improved_answer_guidance}</p><p><strong>Follow-up:</strong> {evaluation.next_question}</p></div>}</div>}</article>}
    {tab === 'decisions' && <article className="coach-card"><p className="coach-eyebrow">CAREER DECISION ENGINE</p><h2>Make the trade-offs explicit</h2><div className="coach-controls"><input value={decisionText} onChange={e => setDecisionText(e.target.value)} placeholder="Should I…?"/><Button onClick={makeDecision} disabled={busy}>Evaluate decision</Button></div>{decision && <div className="coach-result"><h3>Recommendation · {decision.confidence}% confidence</h3><p>{decision.recommendation}</p><p><strong>Based on:</strong></p><ul>{decision.basis.map((item, index) => <li key={index}>{item}</li>)}</ul><p><strong>Next action:</strong> {decision.next_action}</p></div>}</article>}
    </div></div></section>;
}
