from typing import Dict, Any, List, Optional
from sqlalchemy.orm import Session
from app.modules.interviews.models import Interview, InterviewQuestion, InterviewAnswer, AnswerEvaluation
from app.modules.jobs.models import JobTask


def get_interview_data(db: Session, user_id: int, interview_id: int) -> Dict[str, Any]:
    """Controlled READ tool: Retrieves interview session data."""
    interview = db.query(Interview).filter(Interview.id == interview_id, Interview.user_id == user_id).first()
    if not interview:
        return {}
    
    return {
        "id": interview.id,
        "title": interview.title,
        "company": interview.company_name,
        "interview_type": interview.interview_type,
        "status": interview.status,
        "questions_count": len(interview.questions),
    }


def create_preparation_tasks_tool(
    db: Session,
    user_id: int,
    interview_title: str,
    tasks: List[str],
    job_id: Optional[int] = None,
) -> int:
    """Controlled WRITE tool: Schedules preparation tasks into Module 3's task system."""
    created_count = 0
    for task_title in tasks:
        job_task = JobTask(
            user_id=user_id,
            job_id=job_id,
            title=f"Prep [{interview_title}]: {task_title}",
            description=f"Automated prep task generated by Interview Planner Agent for {interview_title}",
            priority="HIGH",
            status="PENDING",
        )
        db.add(job_task)
        created_count += 1
    db.commit()
    return created_count
